apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matomo-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "generic-service.name" . }}
    chart: {{ include "generic-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 10Gi
